"""empty message

Revision ID: 5be03e7b8396
Revises: 59c3b6d122a2
Create Date: 2023-10-30 17:36:03.577760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be03e7b8396'
down_revision = '59c3b6d122a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('convention_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sales_convention_id_conventions'), 'conventions', ['convention_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_convention_id_conventions'), type_='foreignkey')
        batch_op.drop_column('convention_id')

    # ### end Alembic commands ###
