"""Added foreign key

Revision ID: 6268e031531c
Revises: 11f53a448fdb
Create Date: 2023-10-30 15:30:12.406613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6268e031531c'
down_revision = '11f53a448fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sales_inventory_id_Inventory'), 'Inventory', ['inventory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_inventory_id_Inventory'), type_='foreignkey')
        batch_op.drop_column('inventory_id')

    # ### end Alembic commands ###
