"""empty message

Revision ID: 6732627d5ebb
Revises: 0a8d82ca9f66
Create Date: 2023-11-06 14:46:20.808592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6732627d5ebb'
down_revision = '0a8d82ca9f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_convention_id_conventions', type_='foreignkey')
        batch_op.drop_column('convention_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('convention_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_sales_convention_id_conventions', 'conventions', ['convention_id'], ['id'])

    # ### end Alembic commands ###
