"""empty message

Revision ID: 7c49ad9c84de
Revises: 5be03e7b8396
Create Date: 2023-10-31 15:14:07.411327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c49ad9c84de'
down_revision = '5be03e7b8396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inv_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventory', schema=None) as batch_op:
        batch_op.drop_column('inv_image')

    # ### end Alembic commands ###
